---

- name: uninstall old burp package
  package:
    name: burp
    state: absent

- name: uninstall old burp package
  package:
    name: burp-client
    state: absent
  # there is only burp for client and server on FreeBSD
  when: ansible_os_family != "FreeBSD"
