---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: dev_requirements.yml  # this file is at the root of the git project same place as molecule is executed
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: lint.yaml
platforms:

  - name: ansible_test-01
    image: paulfantom/ubuntu-molecule:16.04
    #privileged: True
    command: /sbin/init
    capabilities:
      - SYS_ADMIN    
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"        
    groups:
      - group1

  - name: ansible_test-03
    image: centos/systemd
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    #privileged: True
    groups:
      - group1

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  inventory:
    group_vars:
      master:
        burpsrcext: "zip"
        burp_version: "master"
        burp_server_port_per_operation_bool: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
